# Server configuration
server:
  port: 8080
  contextPath:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,text/css,text/html,text/plain

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot

# Logging configuration
logging:
  level:
    root: info
