# Server configuration
server:
  port: 8080
  contextPath:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,text/css,text/html,text/plain

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: springboot
  datasource:
    primary:
      url: jdbc:mysql://192.168.99.100:3306/springboot
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      testWhileIdle: true
      validationQuery: SELECT 1
      initial-size: 5
      max-idle: 25
      max-active: 25
      test-on-borrow: true
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

# Logging configuration
logging:
  level:
    root: info
